"use client";

import { useState, useRef, useMemo } from "react";
import { trpc } from "@/lib/trpc";
import { Plus, Trash2, Image as ImageIcon, Upload, Pencil, Wand2, Search, Filter, ChevronLeft, ChevronRight, Star } from "lucide-react";
import { motion, AnimatePresence } from "framer-motion";
import { toast } from "sonner";

export default function AdminProductsPage() {
  const [view, setView] = useState("list");
  const [isUploading, setIsUploading] = useState(false);
  const [editingProduct, setEditingProduct] = useState(null);

  const [title, setTitle] = useState("");
  const [handle, setHandle] = useState("");
  const [price, setPrice] = useState("");
  const [isOnSale, setIsOnSale] = useState(false);
  const [compareAtPrice, setCompareAtPrice] = useState("");
  const [isTrending, setIsTrending] = useState(false);
  const [description, setDescription] = useState("");
  const [categoryId, setCategoryId] = useState("");
  const [imageFile, setImageFile] = useState(null);
  const [imagePreview, setImagePreview] = useState("");
  const [tags, setTags] = useState("");

  const fileInputRef = useRef(null);
  const utils = trpc.useUtils();
  const { data: products = [], isLoading: isLoadingProducts } = trpc.commerce.products.list.useQuery();
  const { data: categories = [], isLoading: isLoadingCategories } = trpc.commerce.categories.list.useQuery();

  const [searchTerm, setSearchTerm] = useState("");
  const [categoryFilter, setCategoryFilter] = useState("all");
  const [currentPage, setCurrentPage] = useState(1);
  const itemsPerPage = 10;

  const filteredProducts = useMemo(() => {
    return products.filter((prod) => {
      const matchesSearch = prod.title.toLowerCase().includes(searchTerm.toLowerCase()) || 
                            prod.handle.toLowerCase().includes(searchTerm.toLowerCase());
      const matchesCategory = categoryFilter === "all" || prod.productType === categoryFilter;
      return matchesSearch && matchesCategory;
    });
  }, [products, searchTerm, categoryFilter]);

  const totalPages = Math.ceil(filteredProducts.length / itemsPerPage);
  const paginatedProducts = filteredProducts.slice((currentPage - 1) * itemsPerPage, currentPage * itemsPerPage);

  const createMutation = trpc.admin.createProduct.useMutation({
    onSuccess: () => {
      toast.success("Product created successfully!");
      resetForm();
      setView("list");
      utils.commerce.products.list.invalidate();
    },
    onError: (err) => toast.error(err.message),
  });

  const updateMutation = trpc.admin.updateProduct.useMutation({
    onSuccess: () => {
      toast.success("Product updated successfully!");
      resetForm();
      setView("list");
      utils.commerce.products.list.invalidate();
    },
    onError: (err) => toast.error(err.message),
  });

  const deleteMutation = trpc.admin.deleteProduct.useMutation({
    onSuccess: () => {
      toast.success("Product removed from catalog");
      utils.commerce.products.list.invalidate();
    },
    onError: (err) => toast.error(err.message),
  });

  const autoGenDescMutation = trpc.admin.autoGenerateDescription.useMutation({
    onSuccess: (data) => {
      setDescription(data.description);
      toast.success("Description auto-generated!");
    },
    onError: (err) => toast.error(err.message),
  });

  const autoGenReviewsMutation = trpc.admin.autoGenerateReviews.useMutation({
    onSuccess: () => {
      toast.success("Generated 5-star customer reviews!");
      utils.commerce.products.list.invalidate();
    },
    onError: (err) => toast.error(err.message),
  });

  const resetForm = () => {
    setTitle("");
    setHandle("");
    setPrice("");
    setIsOnSale(false);
    setCompareAtPrice("");
    setIsTrending(false);
    setDescription("");
    setCategoryId("");
    setImageFile(null);
    setImagePreview("");
    setTags("");
    setEditingProduct(null);
  };

  const openEditForm = (prod) => {
    setEditingProduct(prod);
    setTitle(prod.title || "");
    setHandle(prod.handle || "");
    setPrice(prod.priceRange?.min?.amount?.toString() || "");
    setIsOnSale((prod.compareAtPrice && prod.compareAtPrice > prod.priceRange?.min?.amount) ? true : false);
    setCompareAtPrice(prod.compareAtPrice ? prod.compareAtPrice.toString() : "");
    setIsTrending(prod.isTrending || false);
    setDescription(prod.description || "");
    const matchedCat = categories.find(c => c.name.toLowerCase() === (prod.productType || "").toLowerCase());
    setCategoryId(matchedCat?.id || "");
    setImageFile(null);
    setImagePreview(prod.images?.[0]?.url || "");
    setTags((prod.tags || []).join(", "));
    setView("form");
  };

  const handleImageChange = (e) => {
    const file = e.target.files[0];
    if (file) {
      if (file.size > 5 * 1024 * 1024) {
        toast.error("Image must be less than 5MB");
        return;
      }
      setImageFile(file);
      const url = URL.createObjectURL(file);
      setImagePreview(url);
    }
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    if (!categoryId) {
      toast.error("Please select a category");
      return;
    }

    if (isOnSale && parseFloat(compareAtPrice) <= parseFloat(price)) {
      toast.error("Original Price must be HIGHER than Selling Price!");
      return;
    }

    setIsUploading(true);
    let uploadedImageUrl = undefined;

    if (imageFile) {
      const formData = new FormData();
      formData.append("image", imageFile);
      try {
        const res = await fetch("/api/upload", {
          method: "POST",
          body: formData,
        });
        const data = await res.json();
        if (!res.ok) throw new Error(data.error || "Failed to upload image");
        uploadedImageUrl = data.url;
      } catch (err) {
        toast.error(err.message);
        setIsUploading(false);
        return;
      }
    }

    if (editingProduct) {
      const existingImageUrl = editingProduct.images?.[0]?.url;
      updateMutation.mutate({
        productId: editingProduct.id,
        title,
        price: parseFloat(price),
        compareAtPrice: isOnSale && compareAtPrice ? parseFloat(compareAtPrice) : null,
        isTrending,
        description,
        categoryId,
        imageUrl: uploadedImageUrl || existingImageUrl || "",
        tags: tags ? tags.split(",").map(t => t.trim()) : []
      }, {
        onSettled: () => setIsUploading(false)
      });
    } else {
      createMutation.mutate({
        title,
        handle,
        price: parseFloat(price),
        compareAtPrice: isOnSale && compareAtPrice ? parseFloat(compareAtPrice) : null,
        isTrending,
        description,
        categoryId,
        imageUrl: uploadedImageUrl,
        tags: tags ? tags.split(",").map(t => t.trim()) : undefined
      }, {
        onSettled: () => setIsUploading(false)
      });
    }
  };

  const isPending = createMutation.isPending || updateMutation.isPending || isUploading;

  return (
    <div style={{ display: "flex", flexDirection: "column", gap: 28, fontFamily: "'Outfit', sans-serif" }}>

      {/* ── HEADER ── */}
      <div style={{
        display: "flex",
        flexWrap: "wrap",
        alignItems: "center",
        justifyContent: "space-between",
        gap: 16,
        paddingBottom: 20,
        borderBottom: "2px solid #000000"
      }}>
        <div>
          <div style={{ display: "flex", alignItems: "center", gap: 8, marginBottom: 4 }}>
            <div style={{ width: 4, height: 24, background: "#dc2626" }} />
            <h1 style={{ fontSize: "1.8rem", fontWeight: 900, color: "#000000", textTransform: "uppercase", letterSpacing: "-0.03em" }}>
              Denim Catalog Manager
            </h1>
          </div>
          <p style={{ fontSize: "0.7rem", fontWeight: 700, color: "#64748b", letterSpacing: "0.15em", textTransform: "uppercase" }}>
            Total {products.length} Products Active in Store
          </p>
        </div>

        {view === "list" ? (
          <button
            onClick={() => { resetForm(); setView("form"); }}
            style={{
              background: "#dc2626",
              color: "#ffffff",
              border: "2px solid #000000",
              padding: "12px 24px",
              fontWeight: 900,
              fontSize: "0.75rem",
              letterSpacing: "0.18em",
              textTransform: "uppercase",
              cursor: "pointer",
              display: "flex",
              alignItems: "center",
              gap: 8,
              boxShadow: "3px 3px 0px #000000"
            }}
          >
            <Plus style={{ width: 16, height: 16 }} /> Add Denim Product
          </button>
        ) : (
          <button
            onClick={() => { setView("list"); resetForm(); }}
            style={{
              background: "#ffffff",
              border: "2px solid #000000",
              color: "#000000",
              padding: "12px 24px",
              fontWeight: 900,
              fontSize: "0.75rem",
              letterSpacing: "0.18em",
              textTransform: "uppercase",
              cursor: "pointer",
              boxShadow: "3px 3px 0px #000000"
            }}
          >
            Return to List
          </button>
        )}
      </div>

      <AnimatePresence mode="wait">
        {view === "list" ? (
          <motion.div key="list" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} style={{ display: "flex", flexDirection: "column", gap: 20 }}>
            
            {/* ── SEARCH & FILTER CONTROLS ── */}
            <div style={{ display: "flex", flexWrap: "wrap", gap: 12 }}>
              <div style={{ position: "relative", flex: 1, minWidth: 260 }}>
                <Search style={{ position: "absolute", left: 16, top: "50%", transform: "translateY(-50%)", width: 16, height: 16, color: "#94a3b8" }} />
                <input
                  type="text"
                  placeholder="Search products by title or handle..."
                  value={searchTerm}
                  onChange={(e) => setSearchTerm(e.target.value)}
                  style={{
                    width: "100%",
                    background: "#ffffff",
                    border: "2px solid #000000",
                    padding: "12px 16px 12px 44px",
                    color: "#000000",
                    fontWeight: 700,
                    fontSize: "0.85rem",
                    outline: "none",
                    fontFamily: "'Outfit', sans-serif"
                  }}
                  onFocus={e => e.target.style.borderColor = "#dc2626"}
                  onBlur={e => e.target.style.borderColor = "#000000"}
                />
              </div>

              <div style={{ position: "relative", width: 220 }}>
                <Filter style={{ position: "absolute", left: 14, top: "50%", transform: "translateY(-50%)", width: 15, height: 15, color: "#94a3b8" }} />
                <select
                  value={categoryFilter}
                  onChange={(e) => setCategoryFilter(e.target.value)}
                  style={{
                    width: "100%",
                    background: "#ffffff",
                    border: "2px solid #000000",
                    padding: "12px 16px 12px 40px",
                    color: "#000000",
                    fontWeight: 700,
                    fontSize: "0.8rem",
                    outline: "none",
                    cursor: "pointer",
                    fontFamily: "'Outfit', sans-serif"
                  }}
                >
                  <option value="all">All Categories</option>
                  {categories.map(cat => (
                    <option key={cat.id} value={cat.name}>{cat.name}</option>
                  ))}
                </select>
              </div>
            </div>

            {/* ── PRODUCTS TABLE ── */}
            <div style={{
              background: "#ffffff",
              border: "2px solid #000000",
              boxShadow: "4px 4px 0px #000000",
              overflow: "hidden"
            }}>
              <div style={{
                display: "grid",
                gridTemplateColumns: "60px 2.5fr 1.2fr 1fr 1fr 180px",
                padding: "14px 20px",
                borderBottom: "2px solid #000000",
                fontSize: "0.65rem",
                fontWeight: 900,
                color: "#000000",
                letterSpacing: "0.2em",
                textTransform: "uppercase",
                background: "#f8fafc"
              }}>
                <div>Img</div>
                <div>Product Details</div>
                <div>Category</div>
                <div>Price</div>
                <div>Status</div>
                <div style={{ textAlign: "right" }}>Actions</div>
              </div>

              {paginatedProducts.length === 0 ? (
                <div style={{ padding: "64px 0", textAlign: "center", color: "#94a3b8", fontSize: "0.75rem", fontWeight: 700, letterSpacing: "0.15em", textTransform: "uppercase" }}>
                  No catalog items found matching criteria.
                </div>
              ) : (
                paginatedProducts.map(prod => (
                  <div
                    key={prod.id}
                    style={{
                      display: "grid",
                      gridTemplateColumns: "60px 2.5fr 1.2fr 1fr 1fr 180px",
                      padding: "14px 20px",
                      borderBottom: "1px solid #e2e8f0",
                      alignItems: "center"
                    }}
                  >
                    <div>
                      <div style={{ width: 44, height: 44, background: "#f1f5f9", border: "1px solid #000000", overflow: "hidden", display: "flex", alignItems: "center", justifyContent: "center" }}>
                        {prod.images?.[0] ? (
                          <img src={prod.images[0].url} alt={prod.title} style={{ width: "100%", height: "100%", objectFit: "cover" }} />
                        ) : (
                          <ImageIcon style={{ width: 18, height: 18, color: "#94a3b8" }} />
                        )}
                      </div>
                    </div>

                    <div>
                      <div style={{ display: "flex", alignItems: "center", gap: 8 }}>
                        <span style={{ fontSize: "0.85rem", fontWeight: 900, color: "#000000", textTransform: "uppercase" }}>
                          {prod.title}
                        </span>
                        {prod.isTrending && (
                          <span style={{ background: "#dc2626", color: "#ffffff", fontSize: "0.55rem", fontWeight: 900, textTransform: "uppercase", padding: "2px 6px" }}>
                            Trending
                          </span>
                        )}
                      </div>
                      <span style={{ fontSize: "0.65rem", fontWeight: 700, color: "#64748b" }}>
                        /{prod.handle}
                      </span>
                    </div>

                    <div style={{ fontSize: "0.75rem", fontWeight: 800, color: "#475569", textTransform: "uppercase" }}>
                      {prod.productType || "Standard"}
                    </div>

                    <div>
                      <div style={{ fontSize: "0.95rem", fontWeight: 900, color: "#000000" }}>
                        ₹{prod.priceRange?.min?.amount}
                      </div>
                      {prod.compareAtPrice && (
                        <div style={{ fontSize: "0.65rem", fontWeight: 700, color: "#dc2626", textDecoration: "line-through" }}>
                          ₹{prod.compareAtPrice}
                        </div>
                      )}
                    </div>

                    <div>
                      <span style={{ background: "#dcfce7", border: "1px solid #86efac", color: "#16a34a", fontSize: "0.6rem", fontWeight: 900, textTransform: "uppercase", padding: "3px 8px" }}>
                        Active
                      </span>
                    </div>

                    <div style={{ display: "flex", alignItems: "center", justifyContent: "flex-end", gap: 6 }}>
                      <button
                        onClick={() => autoGenReviewsMutation.mutate({ productId: prod.id })}
                        disabled={autoGenReviewsMutation.isPending}
                        style={{
                          background: "#fef3c7",
                          border: "1px solid #d97706",
                          color: "#d97706",
                          padding: "6px 8px",
                          fontSize: "0.6rem",
                          fontWeight: 900,
                          textTransform: "uppercase",
                          cursor: "pointer",
                          display: "flex",
                          alignItems: "center",
                          gap: 4
                        }}
                        title="Generate 5-Star Reviews"
                      >
                        <Star style={{ width: 11, height: 11, fill: "currentColor" }} /> +Reviews
                      </button>

                      <button
                        onClick={() => openEditForm(prod)}
                        style={{
                          background: "#ffffff",
                          border: "1px solid #000000",
                          color: "#000000",
                          padding: "6px 8px",
                          cursor: "pointer"
                        }}
                        title="Edit Item"
                      >
                        <Pencil style={{ width: 13, height: 13 }} />
                      </button>

                      <button
                        onClick={() => {
                          if (confirm("Delete this denim product from catalog?")) deleteMutation.mutate({ productId: prod.id });
                        }}
                        style={{
                          background: "#fee2e2",
                          border: "1px solid #dc2626",
                          color: "#dc2626",
                          padding: "6px 8px",
                          cursor: "pointer"
                        }}
                        title="Delete Item"
                      >
                        <Trash2 style={{ width: 13, height: 13 }} />
                      </button>
                    </div>
                  </div>
                ))
              )}
            </div>

            {/* Pagination */}
            {totalPages > 1 && (
              <div style={{ display: "flex", justifyContent: "center", alignItems: "center", gap: 16, marginTop: 12 }}>
                <button
                  onClick={() => setCurrentPage(p => Math.max(1, p - 1))}
                  disabled={currentPage === 1}
                  style={{ background: "#ffffff", border: "2px solid #000000", color: "#000000", padding: "6px 10px", cursor: "pointer" }}
                >
                  <ChevronLeft style={{ width: 16, height: 16 }} />
                </button>
                <span style={{ fontSize: "0.7rem", fontWeight: 800, color: "#000000", letterSpacing: "0.15em", textTransform: "uppercase" }}>
                  PAGE {currentPage} OF {totalPages}
                </span>
                <button
                  onClick={() => setCurrentPage(p => Math.min(totalPages, p + 1))}
                  disabled={currentPage === totalPages}
                  style={{ background: "#ffffff", border: "2px solid #000000", color: "#000000", padding: "6px 10px", cursor: "pointer" }}
                >
                  <ChevronRight style={{ width: 16, height: 16 }} />
                </button>
              </div>
            )}
          </motion.div>
        ) : (
          <motion.div
            key="form"
            initial={{ opacity: 0, y: 8 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0 }}
            style={{
              background: "#ffffff",
              border: "2px solid #000000",
              padding: "32px",
              boxShadow: "4px 4px 0px #000000"
            }}
          >
            <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", marginBottom: 28, borderBottom: "2px solid #000000", paddingBottom: 16 }}>
              <div>
                <span style={{ fontSize: "0.62rem", fontWeight: 900, color: "#dc2626", letterSpacing: "0.2em", textTransform: "uppercase" }}>
                  {editingProduct ? "EDITING MODE" : "NEW ENTRY"}
                </span>
                <h2 style={{ fontSize: "1.4rem", fontWeight: 900, color: "#000000", textTransform: "uppercase", letterSpacing: "-0.02em" }}>
                  {editingProduct ? `Edit: ${editingProduct.title}` : "Create New Denim Product"}
                </h2>
              </div>
            </div>

            <form onSubmit={handleSubmit} style={{ display: "flex", flexDirection: "column", gap: 24 }}>
              <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(320px, 1fr))", gap: 28 }}>
                
                {/* Left Column */}
                <div style={{ display: "flex", flexDirection: "column", gap: 18 }}>
                  <div>
                    <label style={{ display: "block", fontSize: "0.65rem", fontWeight: 900, color: "#000000", letterSpacing: "0.18em", textTransform: "uppercase", marginBottom: 6 }}>
                      Product Title *
                    </label>
                    <input
                      type="text" value={title}
                      onChange={(e) => {
                        setTitle(e.target.value);
                        if (!editingProduct && (!handle || handle === title.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)+/g, ''))) {
                          setHandle(e.target.value.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)+/g, ''));
                        }
                      }}
                      required
                      placeholder="e.g. Heavyweight Slim Fit Raw Denim"
                      style={{
                        width: "100%",
                        background: "#ffffff",
                        border: "2px solid #000000",
                        padding: "12px 16px",
                        color: "#000000",
                        fontWeight: 700,
                        fontSize: "0.9rem",
                        outline: "none",
                        fontFamily: "'Outfit', sans-serif"
                      }}
                      onFocus={e => e.target.style.borderColor = "#dc2626"}
                      onBlur={e => e.target.style.borderColor = "#000000"}
                    />
                  </div>

                  {!editingProduct && (
                    <div>
                      <label style={{ display: "block", fontSize: "0.65rem", fontWeight: 900, color: "#000000", letterSpacing: "0.18em", textTransform: "uppercase", marginBottom: 6 }}>
                        Handle (URL Slug) *
                      </label>
                      <input
                        type="text" value={handle} onChange={(e) => setHandle(e.target.value)} required
                        placeholder="heavyweight-slim-fit-raw-denim"
                        style={{
                          width: "100%",
                          background: "#ffffff",
                          border: "2px solid #000000",
                          padding: "12px 16px",
                          color: "#000000",
                          fontWeight: 700,
                          fontSize: "0.9rem",
                          outline: "none",
                          fontFamily: "'Outfit', sans-serif"
                        }}
                        onFocus={e => e.target.style.borderColor = "#dc2626"}
                        onBlur={e => e.target.style.borderColor = "#000000"}
                      />
                    </div>
                  )}

                  <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 16 }}>
                    <div>
                      <label style={{ display: "block", fontSize: "0.65rem", fontWeight: 900, color: "#000000", letterSpacing: "0.18em", textTransform: "uppercase", marginBottom: 6 }}>
                        Selling Price (₹) *
                      </label>
                      <input
                        type="number" min="0" step="0.01" value={price} onChange={(e) => setPrice(e.target.value)} required
                        placeholder="1499"
                        style={{
                          width: "100%",
                          background: "#ffffff",
                          border: "2px solid #000000",
                          padding: "12px 16px",
                          color: "#000000",
                          fontWeight: 900,
                          fontSize: "1rem",
                          outline: "none",
                          fontFamily: "'Outfit', sans-serif"
                        }}
                        onFocus={e => e.target.style.borderColor = "#dc2626"}
                        onBlur={e => e.target.style.borderColor = "#000000"}
                      />
                    </div>

                    <div>
                      <label style={{ display: "block", fontSize: "0.65rem", fontWeight: 900, color: "#000000", letterSpacing: "0.18em", textTransform: "uppercase", marginBottom: 6 }}>
                        Category *
                      </label>
                      <select
                        value={categoryId} onChange={(e) => setCategoryId(e.target.value)} required
                        style={{
                          width: "100%",
                          background: "#ffffff",
                          border: "2px solid #000000",
                          padding: "12px 16px",
                          color: "#000000",
                          fontWeight: 700,
                          fontSize: "0.85rem",
                          outline: "none",
                          cursor: "pointer",
                          fontFamily: "'Outfit', sans-serif"
                        }}
                      >
                        <option value="" disabled>Select Category...</option>
                        {categories.map(cat => (
                          <option key={cat.id} value={cat.id}>{cat.name}</option>
                        ))}
                      </select>
                    </div>
                  </div>

                  {/* Toggles */}
                  <div style={{ display: "flex", flexDirection: "column", gap: 10, padding: "14px", background: "#f8fafc", border: "1px solid #e2e8f0" }}>
                    <label style={{ display: "flex", alignItems: "center", gap: 10, cursor: "pointer" }}>
                      <input
                        type="checkbox" checked={isOnSale} onChange={(e) => setIsOnSale(e.target.checked)}
                        style={{ width: 16, height: 16, accentColor: "#dc2626", cursor: "pointer" }}
                      />
                      <span style={{ fontSize: "0.75rem", fontWeight: 800, color: "#000000", textTransform: "uppercase" }}>
                        Enable Sale Discount Price
                      </span>
                    </label>

                    {isOnSale && (
                      <div style={{ marginTop: 6 }}>
                        <label style={{ display: "block", fontSize: "0.62rem", fontWeight: 900, color: "#64748b", letterSpacing: "0.15em", textTransform: "uppercase", marginBottom: 4 }}>
                          Original Price / Compare At (₹)
                        </label>
                        <input
                          type="number" min="0" step="0.01" value={compareAtPrice} onChange={(e) => setCompareAtPrice(e.target.value)}
                          placeholder="2499"
                          style={{
                            width: "100%",
                            background: "#ffffff",
                            border: "1px solid #000000",
                            padding: "10px 14px",
                            color: "#000000",
                            fontWeight: 800,
                            fontSize: "0.9rem",
                            outline: "none"
                          }}
                        />
                      </div>
                    )}

                    <label style={{ display: "flex", alignItems: "center", gap: 10, cursor: "pointer", marginTop: 4 }}>
                      <input
                        type="checkbox" checked={isTrending} onChange={(e) => setIsTrending(e.target.checked)}
                        style={{ width: 16, height: 16, accentColor: "#dc2626", cursor: "pointer" }}
                      />
                      <span style={{ fontSize: "0.75rem", fontWeight: 800, color: "#000000", textTransform: "uppercase" }}>
                        Feature in Top Trending Selection
                      </span>
                    </label>
                  </div>

                  <div>
                    <label style={{ display: "block", fontSize: "0.65rem", fontWeight: 900, color: "#000000", letterSpacing: "0.18em", textTransform: "uppercase", marginBottom: 6 }}>
                      Tags (Comma separated)
                    </label>
                    <input
                      type="text" value={tags} onChange={(e) => setTags(e.target.value)}
                      placeholder="denim, dark wash, slim, raw, stretch"
                      style={{
                        width: "100%",
                        background: "#ffffff",
                        border: "2px solid #000000",
                        padding: "12px 16px",
                        color: "#000000",
                        fontWeight: 700,
                        fontSize: "0.85rem",
                        outline: "none",
                        fontFamily: "'Outfit', sans-serif"
                      }}
                    />
                  </div>
                </div>

                {/* Right Column */}
                <div style={{ display: "flex", flexDirection: "column", gap: 18 }}>
                  <div>
                    <label style={{ display: "block", fontSize: "0.65rem", fontWeight: 900, color: "#000000", letterSpacing: "0.18em", textTransform: "uppercase", marginBottom: 6 }}>
                      Product Imagery *
                    </label>
                    <div
                      onClick={() => fileInputRef.current?.click()}
                      style={{
                        width: "100%",
                        height: 200,
                        border: "2px dashed #dc2626",
                        background: "#fef2f2",
                        display: "flex",
                        flexDirection: "column",
                        alignItems: "center",
                        justifyContent: "center",
                        cursor: "pointer",
                        position: "relative",
                        overflow: "hidden"
                      }}
                    >
                      {imagePreview ? (
                        <img src={imagePreview} alt="Preview" style={{ width: "100%", height: "100%", objectFit: "cover" }} />
                      ) : (
                        <div style={{ textAlign: "center", padding: 20 }}>
                          <Upload style={{ width: 32, height: 32, color: "#dc2626", margin: "0 auto 10px" }} />
                          <p style={{ fontSize: "0.75rem", fontWeight: 900, color: "#000000", letterSpacing: "0.15em", textTransform: "uppercase" }}>
                            Click to Upload Image
                          </p>
                          <p style={{ fontSize: "0.62rem", fontWeight: 600, color: "#64748b", marginTop: 4 }}>
                            PNG, JPG, WEBP up to 5MB
                          </p>
                        </div>
                      )}
                      <input type="file" ref={fileInputRef} onChange={handleImageChange} accept="image/*" style={{ display: "none" }} />
                    </div>
                  </div>

                  <div>
                    <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", marginBottom: 6 }}>
                      <label style={{ fontSize: "0.65rem", fontWeight: 900, color: "#000000", letterSpacing: "0.18em", textTransform: "uppercase" }}>
                        Description & Story
                      </label>
                      <button
                        type="button"
                        onClick={() => {
                          const catName = categories.find(c => c.id === categoryId)?.name;
                          autoGenDescMutation.mutate({ title: title || "Premium Denim Jeans", category: catName });
                        }}
                        disabled={autoGenDescMutation.isPending}
                        style={{
                          background: "#000000",
                          color: "#ffffff",
                          fontSize: "0.6rem",
                          fontWeight: 900,
                          letterSpacing: "0.15em",
                          textTransform: "uppercase",
                          padding: "4px 10px",
                          cursor: "pointer",
                          display: "flex",
                          alignItems: "center",
                          gap: 6
                        }}
                      >
                        <Wand2 style={{ width: 12, height: 12, color: "#dc2626" }} /> Auto-Generate
                      </button>
                    </div>
                    <textarea
                      value={description} onChange={(e) => setDescription(e.target.value)}
                      rows={5}
                      placeholder="Crafted from premium heavy denim with authentic vintage wash..."
                      style={{
                        width: "100%",
                        background: "#ffffff",
                        border: "2px solid #000000",
                        padding: "12px 16px",
                        color: "#000000",
                        fontWeight: 600,
                        fontSize: "0.82rem",
                        lineHeight: 1.6,
                        outline: "none",
                        fontFamily: "'Outfit', sans-serif",
                        resize: "vertical"
                      }}
                      onFocus={e => e.target.style.borderColor = "#dc2626"}
                      onBlur={e => e.target.style.borderColor = "#000000"}
                    />
                  </div>
                </div>
              </div>

              {/* Action Buttons */}
              <div style={{ display: "flex", justifyContent: "flex-end", gap: 12, paddingTop: 16, borderTop: "2px solid #000000" }}>
                <button
                  type="button" onClick={() => setView("list")}
                  style={{
                    background: "#ffffff",
                    border: "2px solid #000000",
                    color: "#000000",
                    padding: "12px 24px",
                    fontWeight: 900,
                    fontSize: "0.75rem",
                    letterSpacing: "0.18em",
                    textTransform: "uppercase",
                    cursor: "pointer"
                  }}
                >
                  Cancel
                </button>
                <button
                  type="submit" disabled={isPending}
                  style={{
                    background: "#dc2626",
                    border: "2px solid #000000",
                    color: "#ffffff",
                    padding: "12px 32px",
                    fontWeight: 900,
                    fontSize: "0.75rem",
                    letterSpacing: "0.18em",
                    textTransform: "uppercase",
                    cursor: "pointer",
                    boxShadow: "3px 3px 0px #000000"
                  }}
                >
                  {isPending ? "Saving..." : editingProduct ? "Save Changes" : "Save Product"}
                </button>
              </div>

            </form>
          </motion.div>
        )}
      </AnimatePresence>

    </div>
  );
}
